In [1]:
import numpy

In [2]:
numpy.array([1,2,3])

array([1, 2, 3])

In [2]:
import numpy as np

In [4]:
a =np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [8]:
b=np.array([[1,2,3],[1,2,3]])

In [9]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [10]:
b.shape

(2, 3)

In [11]:
a

array([1, 2, 3])

In [13]:
a.shape

(3,)

In [14]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [16]:
b.dtype

dtype('int32')

In [17]:
b.ndim

2

In [18]:
print(type(a))

<class 'numpy.ndarray'>


In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
C= range(10000)

In [26]:
%timeit [i**3 for i in C]

22.9 ms ± 4.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [29]:
C_numpy = np.arange(10000)

In [30]:
%timeit C_numpy**3

91.8 µs ± 4.73 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [34]:
11 = range(10000)
12 = [i**2 for i in range(10000)]

SyntaxError: can't assign to literal (<ipython-input-34-a02368e1c9c7>, line 1)

In [36]:
%timeit list(map(lambda x,y: x*y, 11, 12))

TypeError: 'int' object is not iterable

In [37]:
a1 = np.array(11)
b1 = np.array(12)

In [38]:
%timeit a1*b1

2.29 µs ± 53.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [47]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [50]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [51]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.full((3,3),2.2,dtype= np.int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [58]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [59]:
v=np.array([1,2,3])

In [60]:
v

array([1, 2, 3])

In [61]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [90]:
50*np.random.random() +2

44.07100876855144

In [92]:
np.random.random([3,3])

array([[0.9582442 , 0.48430179, 0.77230228],
       [0.35923757, 0.09157237, 0.28082653],
       [0.81193347, 0.66456595, 0.99105134]])

In [4]:
 a = np.linspace(1,50,100)

In [5]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [6]:
a.itemsize

8

In [10]:
b=np.arange(18).reshape(2,3,3)

In [11]:
b.shape

(2, 3, 3)

In [13]:
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [14]:
a=np.array([2,4,6,8,10,12,14,16])

In [15]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [16]:
a[0]

2

In [17]:
a[2
 ]

6

In [18]:
a[[4,4,6]]

array([10, 10, 14])

In [19]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [20]:
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [21]:
a[2:5]

array([ 6,  8, 10])

In [22]:
a[::2]

array([ 2,  6, 10, 14])

In [23]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a[2,2]

9

In [27]:
a>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [28]:
a[(a>2) &(a<5)]

array([3, 4])

In [33]:
a=np.arange(10)

In [34]:
b=a

In [35]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
b[0]=11


In [38]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [43]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [44]:
np.shares_memory(a,b)

True

In [45]:
a=np.arange(10)

In [48]:
b=a.copy()

In [49]:
b

array([0])

In [50]:
a

array([0])

In [52]:
np.shares_memory(a,b)

False

In [53]:
a=np.array([[1,2,3],[4,5,6]])

In [54]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
b=np.array([[7,8,9],[10,11,12]])

In [58]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [59]:
a == b

array([[False, False, False],
       [False, False, False]])

In [60]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [63]:
a=np.arange(1,10)

In [65]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [66]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [67]:
np.sum(a)

45

In [68]:
np.median(a)

5.0

In [69]:
np.std(a)

2.581988897471611

In [71]:
a=np.arange(1,10).reshape(3,3)

In [72]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.linalg.det(a)

-9.51619735392994e-16

In [75]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [76]:
b=a.T

In [77]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [78]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [80]:
a= np.array([1,1,0], dtype=bool)
b=np.array([1,0,1], dtype=bool)

In [83]:
np.logical_or(a,b)

array([ True,  True,  True])

In [84]:
np.logical_and(a,b)

array([ True, False, False])

In [85]:
a == a

array([ True,  True,  True])

In [87]:
np.all(a==a)

True

In [89]:
a=np.array([[1,2],[3,4]])

In [90]:
a

array([[1, 2],
       [3, 4]])

In [92]:
a.sum()

10

In [94]:
a.sum(axis=0)

array([4, 6])

In [95]:
a.sum(axis=1)

array([3, 7])

In [96]:
a.max()

4

In [97]:
a.argmax()

3

In [98]:
a

array([[1, 2],
       [3, 4]])

In [99]:
a.shape

(2, 2)

In [100]:
a=np.arange(10)

In [101]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a.shape

(10,)

In [103]:
a[:,np.newaxis].shape

(10, 1)

In [104]:
np.short(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)